name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Install Dependencies
      run: apt install -y coinor-libcbc-dev 
    - name: Build
      run: cd rewrite-eqsat; cargo build --verbose
    - name: Run tests
      run: cd rewrite-eqsat; cargo test --verbose
